In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
df=pd.read_csv("/content/ev_car_India_dataset.csv")

In [4]:
df.head()

      Brand          Model  Price  Range  Power  Battery
0    Maruti  SuzukieVitara  15.99    440  142.0     49.0
1      Tata        PunchEV   9.69    275   87.0     30.0
2  Mahindra          XEV9e  21.90    542  228.0     59.0
3  Mahindra            BE6  18.90    557  228.0     59.0
4        MG      WindsorEV  14.00    332  134.0     38.0

In [5]:
df.shape

(26, 6)

In [6]:
df.isnull().sum()

Brand      0
Model      0
Price      0
Range      0
Power      0
Battery    0
dtype: int64

In [7]:
X=df.drop("Price",axis=1)
y=df["Price"]

In [8]:
df["Model"].unique()

array(['SuzukieVitara', 'PunchEV', 'XEV9e', 'BE6', 'WindsorEV', 'CometEV',
       'Cyberster', 'NexonEV', 'HarrierEV', 'TiagoEV', 'CretaElectric',
       'MobilityEva', 'EV6', 'ZSEV', 'VF7', 'CurvvEV', 'VF6', 'M9',
       'Sealion7', 'Seal', 'iX1', 'EX30', 'Atto3', 'XUV400EV', 'i4',
       'UrbanCruiserEBELLA'], dtype=object)

In [9]:
categorical=["Brand" ,"Model"]
numerical=["Range","Power","Battery"]

In [11]:
preprocessor=ColumnTransformer([
      ("categorical",
       OneHotEncoder(handle_unknown="ignore"),
       categorical),

      ("numerical",
       StandardScaler(),
       numerical)
])

In [13]:
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
alphas=[0.01,0.1,1,10,100]
results=[]
for alpha in alphas:
  model=Pipeline([
      ("preprocessor",preprocessor),
      ("ridge",Ridge(alpha=alpha))
  ])

  model.fit(X_train,y_train)

In [24]:
train_pred=model.predict(X_train)
test_pred=model.predict(X_test)

In [25]:
train_mae=mean_absolute_error(y_train,train_pred)
train_rmse=np.sqrt(mean_squared_error(y_train,train_pred))
train_r2=r2_score(y_train,train_pred)

In [26]:
test_mae=mean_absolute_error(y_test,test_pred)
test_rmse=np.sqrt(mean_squared_error(y_test,test_pred))
test_r2=r2_score(y_test,test_pred)

In [27]:
results.append([
    alpha,
    train_mae,
    train_rmse,
    train_r2,
    test_mae,
    test_rmse,
    test_r2
])

In [28]:
print(results)

[[100, 13.00417592430386, np.float64(14.996609391680673), 0.46828394675565943, 16.214627227800246, np.float64(18.564924205557084), 0.34342687977994]]

In [30]:
results=pd.DataFrame(results,columns=[
    "Alpha",
    "Train_MAE",
    "Train_RMSE",
    "Train_R2",
    "Test_MAE",
    "Test_RMSE",
    "Test_R2"
])

In [31]:
print("\nRidge Regression Results:")
print(results)

Ridge Regression Results:
   Alpha  Train_MAE  Train_RMSE  Train_R2  Test_MAE  Test_RMSE  Test_R2
0    100        NaN         NaN       NaN       NaN        NaN      NaN